(cl:defpackage sensors-srv
  (:use )
  (:export
   "REGISTRATIONSERVICE"
   "<REGISTRATIONSERVICE-REQUEST>"
   "REGISTRATIONSERVICE-REQUEST"
   "<REGISTRATIONSERVICE-RESPONSE>"
   "REGISTRATIONSERVICE-RESPONSE"
  ))

