// Generated by gencpp from file arduino_control/ArduinoControl.msg
// DO NOT EDIT!


#ifndef ARDUINO_CONTROL_MESSAGE_ARDUINOCONTROL_H
#define ARDUINO_CONTROL_MESSAGE_ARDUINOCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduino_control
{
template <class ContainerAllocator>
struct ArduinoControl_
{
  typedef ArduinoControl_<ContainerAllocator> Type;

  ArduinoControl_()
    : dir(0.0)
    , speed(0.0)  {
    }
  ArduinoControl_(const ContainerAllocator& _alloc)
    : dir(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef double _dir_type;
  _dir_type dir;

   typedef double _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::arduino_control::ArduinoControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_control::ArduinoControl_<ContainerAllocator> const> ConstPtr;

}; // struct ArduinoControl_

typedef ::arduino_control::ArduinoControl_<std::allocator<void> > ArduinoControl;

typedef boost::shared_ptr< ::arduino_control::ArduinoControl > ArduinoControlPtr;
typedef boost::shared_ptr< ::arduino_control::ArduinoControl const> ArduinoControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_control::ArduinoControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_control::ArduinoControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arduino_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arduino_control': ['/home/daniel/Documents/catkin_ws/src/arduino_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arduino_control::ArduinoControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_control::ArduinoControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_control::ArduinoControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_control::ArduinoControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_control::ArduinoControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_control::ArduinoControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_control::ArduinoControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7528cb4c6fd33cf9e3157bf84136adec";
  }

  static const char* value(const ::arduino_control::ArduinoControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7528cb4c6fd33cf9ULL;
  static const uint64_t static_value2 = 0xe3157bf84136adecULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_control::ArduinoControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_control/ArduinoControl";
  }

  static const char* value(const ::arduino_control::ArduinoControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_control::ArduinoControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dir			#Direction in degrees with 0 degrees being forward\n\
float64 speed		#Magnitude of direction -1 to 1\n\
";
  }

  static const char* value(const ::arduino_control::ArduinoControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_control::ArduinoControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dir);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ArduinoControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_control::ArduinoControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_control::ArduinoControl_<ContainerAllocator>& v)
  {
    s << indent << "dir: ";
    Printer<double>::stream(s, indent + "  ", v.dir);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_CONTROL_MESSAGE_ARDUINOCONTROL_H
